# Generated by Django 3.0.6 on 2020-06-13 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Beat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beat',
            options={'ordering': ('name',), 'verbose_name': 'Бит', 'verbose_name_plural': 'Биты'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.RenameField(
            model_name='beat',
            old_name='date',
            new_name='created',
        ),
        migrations.AddField(
            model_name='beat',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена в долларах'),
        ),
        migrations.AddField(
            model_name='beat',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterIndexTogether(
            name='beat',
            index_together={('id', 'url')},
        ),
    ]
