# Generated by Django 3.0.7 on 2020-07-25 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Beat', '0002_auto_20200613_2257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beat',
            name='updated',
        ),
        migrations.AddField(
            model_name='beat',
            name='url_to_cloud',
            field=models.URLField(default='', verbose_name='Ссылка на ФАЙЛ в облаке'),
        ),
    ]
